# Generated by Django 3.1 on 2020-08-14 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pe_ratio', models.FloatField()),
                ('ten_year_price', models.FloatField()),
                ('growth_rate_wsj', models.FloatField()),
                ('growth_rate_yahoo', models.FloatField()),
                ('ttm_eps', models.FloatField()),
                ('future_pe_ratio_calculated', models.FloatField()),
                ('future_pe_ratio_analyst', models.FloatField()),
                ('website', models.TextField()),
                ('sp_500', models.BooleanField()),
                ('dow_jones', models.BooleanField()),
                ('nasdaq_composite', models.BooleanField()),
                ('russell_2000', models.BooleanField()),
                ('sector', models.TextField()),
                ('tick', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('catergory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='stocks.category')),
            ],
        ),
    ]
